### YamlMime:FAQ
metadata:
  title: 配置常见问题解答
  description: 获取有关 Azure 应用服务配置和管理问题的常见问题解答。
  author: genlin
  manager: dcscontentpm
  tags: top-support-issue
  ms.assetid: 2fa5ee6b-51a6-4237-805f-518e6c57d11b
  ms.topic: article
  ms.service: app-service
  ms.date: 10/30/2018
  ms.author: genli
  ms.custom: devx-track-azurepowershell
  ms.openlocfilehash: 6f8d30011a19c6d8210d9c63f4378a66237fe024
  ms.sourcegitcommit: 05dd6452632e00645ec0716a5943c7ac6c9bec7c
  ms.translationtype: HT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 08/17/2021
  ms.locfileid: "122253353"
title: Azure Web 应用配置及管理常见问题解答
summary: >
  本文对 [Azure App Service Web 应用功能](https://azure.microsoft.com/services/app-service/web/)配置和管理常见问题 (FAQ) 进行了解答。


  [!INCLUDE [support-disclaimer](../../includes/support-disclaimer.md)]
sections:
- name: 忽略
  questions:
  - question: >
      如果需要移动应用服务资源，是否有什么限制需要注意？
    answer: >
      如果打算将应用服资源转移到新的资源组或订阅，有一些限制需要注意。 有关详细信息，请参阅[应用服务限制](../azure-resource-manager/management/move-limitations/app-service-move-limitations.md)。
  - question: >
      如何将自定义域名用于 Web 应用？
    answer: >
      有关将自定义域名用于 Azure Web 应用的常见问题解答，请参阅我们的七分钟视频[添加自定义域名](https://channel9.msdn.com/blogs/Azure-App-Service-Self-Help/Add-a-Custom-Domain-Name)。 该视频演示如何添加自定义域名。 它介绍如何将自己的 URL（而不是 *.azurewebsites.net URL）用于应用服务 Web 应用。 还可以查看有关[如何映射自定义域名](app-service-web-tutorial-custom-domain.md)的详细演练。
  - question: >
      如何为 Web 应用购买新的自定义域？
    answer: >
      若要了解如何为应用服务 Web 应用购买和设置自定义域，请参阅[在应用服务中配置和配置自定义域名](manage-custom-dns-buy-domain.md)。
  - question: >
      如何上传和配置 Web 应用的现有 TLS/SSL 证书？
    answer: >
      若要了解如何上传和设置现有的自定义 TLS/SSL 证书，请参阅[将 TLS/SSL 证书添加到应用服务应用](configure-ssl-certificate.md)。
  - question: >
      如何在 Azure 中为 Web 应用购买和配置新的 TLS/SSL 证书？
    answer: >
      若要了解如何为应用服务 Web 应用购买和设置 TLS/SSL 证书，请参阅[将 TLS/SSL 证书添加到应用服务应用](configure-ssl-certificate.md)。
  - question: >
      如何移动 Application Insights 资源？
    answer: >
      当前，Azure Application Insights 不支持移动操作。 如果原始资源组包括 Application Insights 资源，则无法移动该资源。 如果在尝试移动应用服务应用时包括了 Application Insights 资源，则整个移动操作会失败。 不过，即使 Application Insights 和应用服务计划不与应用位于同一资源组中，应用也可以正常运行。


      有关详细信息，请参阅[应用服务限制](../azure-resource-manager/management/move-limitations/app-service-move-limitations.md)。
  - question: >
      可从何处找到指南清单，了解有关资源移动操作的详细信息？
    answer: >
      [应用服务限制](../azure-resource-manager/management/move-limitations/app-service-move-limitations.md)说明如何将资源移到新订阅或同一订阅的新资源组中。 可以获取有关资源移动清单的信息，了解哪些服务支持移动操作，并了解有关应用服务限制及其他主题的详细信息。
  - question: >
      如何为 Web 应用设置服务器时区？
    answer: >
      为 Web 应用设置服务器时区：


      1. 在 Azure 门户的应用服务订阅中，转到“应用程序设置”菜单。

      2. 在“应用设置”下，添加此设置：
          * 键 = WEBSITE_TIME_ZONE
          * 值 = *所需时区*
      3. 选择“保存” 。


      对于在 Windows 上运行的应用服务，请参阅 Windows `tzutil /L` 命令的输出。 使用每个项的第二行中的值。 例如：“汤加标准时间”。 其中的某些值也列在[默认时区](/windows-hardware/manufacture/desktop/default-time-zones)的“时区”列中。


      对于在 Linux 上运行的应用程序服务，请在 [IANA TZ 数据库](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)中设置值。 例如：“美国/Adak”。
  - question: >
      为什么连续 Web 作业有时会失败？
    answer: >
      默认情况下，如果 Web 应用已处于空闲状态相当一段时间，则其处于未加载的状态。 这样可以让系统节省资源。 在基本和标准计划中，可打开“Always On”设置，保持 Web 应用一直处于已加载的状态。 如果 Web 应用运行连续的 Web 作业，应启用“Always On”；否则，这些 Web 作业可能无法可靠运行。 有关详细信息，请参阅[创建连续运行的 Web 作业](webjobs-create.md#CreateContinuous)。
  - question: >
      如何获取 Web 应用的出站 IP 地址？
    answer: >
      获取 Web 应用出站 IP 地址列表：


      1. 在 Azure 门户中的 Web 应用边栏选项卡上，转到“属性”菜单。

      2. 搜索 **出站 IP 地址**。


      随即显示出站 IP 地址列表。


      如果你的网站在应用服务环境中承载，则若要了解如何获取出站 IP 地址，请参阅[出站网络地址](environment/app-service-app-service-environment-network-architecture-overview.md#outbound-network-addresses)。
  - question: >
      如何获取 Web 应用的保留或专用入站 IP 地址？
    answer: >
      若要为针对 Azure 应用网站发出的入站调用设置专用或保留 IP 地址，请安装并配置基于 IP 的 TLS/SSL 证书。


      请注意，若要将专用或保留的 IP 地址用于入站调用，应用服务计划必须包含在基本或更高的服务计划中。
  - question: "是否可以导出应用服务证书以在 Azure 外部使用（如用于在其他位置承载的网站）？ \n"
    answer: >
      是的，可以导出这些证书以在 Azure 外部使用。 有关详细信息，请参阅[应用服务证书和自定义域的常见问题解答](https://social.msdn.microsoft.com/Forums/azure/f3e6faeb-5ed4-435a-adaa-987d5db43b80/faq-on-app-service-certificates-and-custom-domains?forum=windowsazurewebsitespreview)。
  - question: >
      是否可以导出应用服务证书以用于其他 Azure 云服务？
    answer: >
      门户针对通过 Azure Key Vault 将应用服务证书部署到应用服务应用提供一流的体验。 但是，我们从客户处收到了在应用服务平台外部使用这些证书（例如，用于 Azure 虚拟机）的请求。 若要了解如何创建应用服务证书的本地 PFX 副本以便可以将证书用于其他 Azure 资源，请参阅[创建应用服务证书的本地 PFX 副本](https://blogs.msdn.microsoft.com/appserviceteam/2017/02/24/creating-a-local-pfx-copy-of-app-service-certificate/)。


      有关详细信息，请参阅[应用服务证书和自定义域的常见问题解答](https://social.msdn.microsoft.com/Forums/azure/f3e6faeb-5ed4-435a-adaa-987d5db43b80/faq-on-app-service-certificates-and-custom-domains?forum=windowsazurewebsitespreview)。
  - question: >
      尝试备份 Web 应用时，为何出现“部分成功”的消息？
    answer: >
      备份失败的一个常见原因是应用程序正在使用某些文件。 执行备份时，正在使用的文件会被锁定。 这会阻止对这些文件的备份操作，并可能导致“部分成功”状态。 可以通过将文件从备份过程中排除来防止这种情况发生。 可以选择仅备份所需文件。 有关详细信息，请参阅 [Azure Web 应用仅备份站点的重要部分](https://zainrizvi.io/blog/creating-partial-backups-of-your-site-with-azure-web-apps/)。
  - question: >
      如何从 HTTP 响应中删除标头？
    answer: >
      若要移删除 HTTP 响应的标头，请更新站点的 web.config 文件。 有关详细信息，请参阅[在 Azure 网站上删除标准服务器标头](https://azure.microsoft.com/blog/removing-standard-server-headers-on-windows-azure-web-sites/)。
  - question: >
      应用服务是否符合 PCI 标准 3.0 和 3.1？
    answer: >
      目前，Azure App Service 的 Web 应用功能符合 PCI 数据安全标准 (DSS) 3.0 版级别 1。 PCI DSS 3.1 版正在设计之中。 我们正在计划如何采用最新标准。


      PCI DSS 3.1 版证书要求禁用传输层安全性 (TLS) 1.0。 目前，大多数应用服务计划无法禁用 TLS 1.0。 但是，如果使用应用服务环境，或者愿意将工作负荷迁移到应用服务环境，则可以更好地控制环境。 这涉及到通过与 Azure 支持部门联系来禁用 TLS 1.0。 在不久的将来，我们计划使用户可以访问这些设置。


      有关详细信息，请参阅 [Microsoft Azure App Service Web 应用符合 PCI 标准 3.0 和 3.1](https://support.microsoft.com/help/3124528)。
  - question: >
      如何使用过渡环境和部署槽位？
    answer: >
      在标准版和高级版应用服务计划中，将 Web 应用部署到应用服务时，可部署到单独的部署槽位而不是默认的生产槽位。 部署槽是具有自己的主机名的动态 Web 应用。 两个部署槽（包括生产槽）之间的 Web 应用内容与配置元素可以交换。


      有关使用部署槽位的详细信息，请参阅[在应用服务中设置过渡环境](deploy-staging-slots.md)。
  - question: >
      如何访问和查看 Web 作业日志？
    answer: >
      查看 Web 作业日志：


      1. 登录到 Kudu 网站 (`https://*yourwebsitename*.scm.azurewebsites.net`)。

      2. 选择 Web 作业。

      3. 选择“切换输出”按钮。

      4. 若要下载输出文件，请选择“下载”链接。

      5. 对于单个运行，选择“单个调用”。

      6. 选择“切换输出”按钮。

      7. 选择下载链接。
  - question: >
      我在尝试对 SQL Server 使用混合连接。 为什么会看到消息“System.OverflowException: 算术运算导致了溢出”？
    answer: >
      如果使用混合连接访问 SQL Server，则 2016 年 5 月 10 的 Microsoft.NET 更新可能会导致连接失败。 你可能会看到此消息：


      ```

      Exception: System.Data.Entity.Core.EntityException: The underlying provider failed on Open. —> System.OverflowException: Arithmetic operation resulted in an overflow. or (64 bit Web app) System.OverflowException: Array dimensions exceeded supported range, at System.Data.SqlClient.TdsParser.ConsumePreLoginHandshake

      ```


      ### <a name="resolution"></a>解决方法


      该异常是由于混合连接管理器存在问题而导致，该问题现已修复。 请务必[更新混合连接管理器](https://go.microsoft.com/fwlink/?LinkID=841308)以解决此问题。
  - question: >
      如何添加 URL 重写规则？
    answer: >
      若要添加 URL 重写规则，请使用 **wwwroot** 文件夹中的相关配置条目创建一个 web.config 文件。 有关详细信息，请参阅 [Azure 应用服务：了解 URL 重写](/archive/blogs/madhurabharadwaj/azure-app-services-understanding-url-re-write)。
  - question: >
      如何控制应用服务的入站流量？
    answer: >
      在站点层面上，有两种方法可用于控制应用服务的入站流量：


      * 启用动态 IP 限制。 若要了解如何启用动态 IP 限制，请参阅[适用于 Azure 网站的 IP 和域限制](https://azure.microsoft.com/blog/ip-and-domain-restrictions-for-windows-azure-web-sites/)。

      * 开启“模块安全”。 若要了解如何开启模块安全，请参阅 [Azure 网站上的 ModSecurity Web 应用程序防火墙](https://azure.microsoft.com/blog/modsecurity-for-azure-websites/)。


      如果使用应用服务环境，则可以使用 [Barracuda 防火墙](https://azure.microsoft.com/blog/configuring-barracuda-web-application-firewall-for-azure-app-service-environment/)。
  - question: >
      如何在应用服务 Web 应用中封锁端口？
    answer: >
      在应用服务共享租户环境中，由于基础结构的性质，无法封锁特定端口。 TCP 端口 4020、4022 和 4024 也可能打开，用于 Visual Studio 远程调试。


      在应用服务环境中，可完全控制入站和出站流量。 可以使用网络安全组限制或阻止特定端口。 有关应用服务环境的详细信息，请参阅[应用服务环境简介](https://azure.microsoft.com/blog/introducing-app-service-environment/)。
  - question: >
      如何捕获 F12 跟踪？
    answer: >
      捕获 F12 跟踪有两种方法：


      * F12 HTTP 跟踪

      * F12 控制台输出


      ### <a name="f12-http-trace"></a>F12 HTTP 跟踪


      1. 在 Internet Explorer 中，转到网站。 请务必先登录，然后再执行后续步骤。 否则，F12 跟踪会捕获敏感登录数据。

      2. 按 F12。

      3. 确认已选中“网络”选项卡，然后选中绿色“播放”按钮。

      4. 执行可重现问题的步骤。

      5. 选择红色“停止”按钮。

      6. 选择“保存”按钮（磁盘图标），然后保存 HAR 文件（在 Internet Explorer 和 Microsoft Edge 中），或右键单击 HAR 文件，然后选择“保存为包含内容的 HAR”（在 Chrome 中）。


      ### <a name="f12-console-output"></a>F12 控制台输出


      1. 选择“控制台”选项卡。

      2. 对于每个至少包含一项的选项卡，选择选项卡（“错误”、“警告”或“信息”）。 如果未选中选项卡，移开光标时，选项卡图标呈灰色或黑色。

      3. 右键单击窗格中的信息区域，然后选择“全部复制”。

      4. 将复制的文本粘贴到文件中，然后保存该文件。


      若要查看 HAR 文件，可以使用 [HAR 查看器](http://www.softwareishard.com/har/viewer/)。
  - question: >
      在我尝试将应用服务 Web 应用到连接到与 ExpressRoute 连接的虚拟网络时，为何会遇到错误？
    answer: >
      如果尝试将 Azure Web 应用连接到与 Azure ExpressRoute 连接的虚拟网络，则会失败。 此时会显示以下消息：“网关不是 VPN 网关”。


      当前，无法与连接到 ExpressRoute 的虚拟网络建立点到站点 VPN 连接。 对于同一虚拟网络而言，点到站点 VPN 和 ExpressRoute 不能共存。 有关详细信息，请参阅 [ExpressRoute 和站点到站点 VPN 连接限制和局限性](../expressroute/expressroute-howto-coexist-classic.md#limits-and-limitations)。
  - question: >
      如何将应用服务 Web 应用连接到具有静态路由（基于策略）网关的虚拟网络？
    answer: "当前，不支持将应用服务 Web 应用连接到具有静态路由（基于策略）网关的虚拟网络。 如果目标虚拟网络已经存在，必须在连接到应用之前借助动态路由网关使网络处于点到站点 VPN 启用状态。 如果网关设置为静态路由，则无法启用点到站点 VPN。 \n\n有关详细信息，请参阅[将应用与 Azure 虚拟网络进行集成](web-sites-integrate-with-vnet.md)。\n"
  - question: >
      在应用服务环境中，为何即使有两个可用的辅助角色，也只能创建一个应用服务计划？
    answer: >
      为了提供容错能力，应用服务环境要求每个辅助角色池至少需要一个额外的计算资源。 无法为额外的计算资源分配工作负荷。


      有关详细信息，请参阅[如何创建应用服务环境](environment/app-service-web-how-to-create-an-app-service-environment.md)。
  - question: >
      在尝试创建应用服务环境时，为何遇到超时？
    answer: >
      优势，创建应用服务环境会失败。 在这种情况下，你会在活动日志中看到以下错误：

      ```

      ResourceID: /subscriptions/{SubscriptionID}/resourceGroups/Default-Networking/providers/Microsoft.Web/hostingEnvironments/{ASEname}

      Error:{"error":{"code":"ResourceDeploymentFailure","message":"The resource provision operation did not complete within the allowed timeout period."}}

      ```


      若要解决此问题，请确保不存在以下任何情况：

      * 子网太小。

      * 子网非空。

      * ExpressRoute 会阻碍应用服务环境的网络连接要求。

      * 错误的网络安全组会阻碍应用服务环境的网络连接要求。

      * 强制隧道处于打开状态。


      有关详细信息，请参阅[部署（创建）新 Azure 应用服务环境时的常见问题](/archive/blogs/waws/most-frequent-issues-when-deploying-creating-a-new-azure-app-service-environment-ase)。
  - question: >
      为什么无法删除应用服务计划？
    answer: >
      如果应用服务计划与任何应用服务应用相关联，则无法删除此应用服务计划。 删除应用服务计划前，请从应用服务计划中删除所有关联的应用服务应用。
  - question: >
      如何计划 Web 作业？
    answer: "可以使用 Cron 表达式创建计划的 Web 作业：\n\n1. 创建一个 settings.job 文件。\n2. 在此 JSON 文件中，使用 Cron 表达式将计划属性包括在内： \n    ```json\n    { \"schedule\": \"{second}\n    {minute} {hour} {day}\n    {month} {day of the week}\" }\n    ```\n\n有关计划的 Web 作业的详细信息，请参阅[使用 Cron 表达式创建计划的 Web 作业](webjobs-create.md#CreateScheduledCRON)。\n"
  - question: >
      如何对应用服务应用执行渗透测试？
    answer: >
      若要执行渗透测试，请[提交请求](https://portal.msrc.microsoft.com/engage/pentest)。
  - question: >
      如何为使用流量管理器的应用服务 Web 应用配置自定义域名？
    answer: >
      若要了解如何将自定义域名用于使用 Azure 流量管理器实现负载均衡的应用服务应用，请参阅[为使用流量管理器的 Azure Web 应用配置自定义域名](configure-domain-traffic-manager.md)。
  - question: >
      我的应用服务证书被标记为存在欺诈。 如何解决此问题？
    answer: "[!INCLUDE [updated-for-az](../../includes/updated-for-az.md)]\n\n在应用服务证书购买的域验证过程中，可能会看到以下消息：\n\n“你的证书已被标记为可能存在欺诈。 请求当前正在审查中。 如果证书未在 24 小时内变为可用，请联系 Azure 支持部门。”\n\n如该消息所示，此欺诈验证过程可能需要最多 24 小时才能完成。 在此期间，你会继续看到该消息。\n\n如果你的应用服务证书在 24 小时后继续显示此消息，请运行以下 PowerShell 脚本。 该脚本会联系[证书提供商](https://www.godaddy.com/)直接解决问题。\n\n```powershell\nConnect-AzAccount\nSet-AzContext -SubscriptionId <subId>\n$actionProperties = @{\n    \"Name\"= \"<Customer Email Address>\"\n    };\nInvoke-AzResourceAction -ResourceGroupName \"<App Service Certificate Resource Group Name>\" -ResourceType Microsoft.CertificateRegistration/certificateOrders -ResourceName \"<App Service Certificate Resource Name>\" -Action resendRequestEmails -Parameters $actionProperties -ApiVersion 2015-08-01 -Force   \n```\n"
  - question: >
      应用服务中是如何进行身份验证和授权的？
    answer: >
      有关应用服务中的身份验证和授权的详细文档，请参阅各种标识提供者登录的文档：

      * [Azure Active Directory](configure-authentication-provider-aad.md)

      * [Facebook](configure-authentication-provider-facebook.md)

      * [Google](configure-authentication-provider-google.md)

      * [Microsoft 帐户](configure-authentication-provider-microsoft.md)

      * [Twitter](configure-authentication-provider-twitter.md)
  - question: >
      如何将默认的 *.azurewebsites.net 域重定向到我的 Azure Web 应用的自定义域？
    answer: >
      在 Azure 中使用 Web 应用创建新网站时，会向站点分配默认的 sitename.azurewebsites.net 域。 如果将自定义主机名添加到站点，并且不希望用户能够访问默认的 *.azurewebsites.net 域，则可以重定向默认 URL。 若要了解如何将源自网站默认域的所有通信流重定向到自定义域，请参阅[将默认域重定向到 Azure Web 应用中的自定义域](https://zainrizvi.io/blog/block-default-azure-websites-domain/)。
  - question: >
      如何确定应用服务中安装的 .NET 版本？
    answer: >
      若要查找应用服务中安装的 Microsoft.NET 版本，最快的方法是使用 Kudu 控制台。 可以从门户或使用应用服务应用的 URL，来访问 Kudu 控制台。 有关详细说明，请参阅[确定应用服务中安装的 .NET 版本](/archive/blogs/waws/how-to-determine-the-installed-net-version-in-azure-app-services)。
  - question: >
      为什么自动缩放不按预期方式工作？
    answer: >
      如果 Azure 自动缩放未按预期方式缩放 web 应用，可能会陷入一种困境，在这种情况下，建议主动选择不进行缩放以避免由“不稳定”引起的无限循环。 这种情况通常是因扩展阈值和缩小阈值之间的差值不足所致。 若要了解如何避免“波动”以及如何了解其他自动缩放最佳做法，请参阅[自动缩放最佳做法](../azure-monitor/autoscale/autoscale-best-practices.md#autoscale-best-practices)。
  - question: >
      为什么自动缩放有时仅进行部分缩放？
    answer: >
      当指标超过预配置的限值时，将触发自动缩放。 有时可能会发现，与预期相比，仅填充了部分容量。 当所需的实例数无法实现时，则可能会发生这种情况。 在这种情况下，自动缩放使用可用的实例数进行部分填充。 然后，自动缩放运行重新平衡逻辑，以获取更多容量。 它会分配剩余实例。 请注意，这可能需要几分钟的时间。


      如果在几分钟后未看到预期数量的实例，则可能是因为部分重填已足以使指标处于边界内。 或者，可能自动缩放已执行缩小操作，因为已达到度量值的下限。


      如果以上情况都不存在而问题仍然存在，请提交支持请求。
  - question: >
      如何为内容启用 HTTP 压缩？
    answer: >
      若要同时为静态和动态内容类型启用压缩，请将以下代码添加到应用程序级别的 web.config 文件：


      ```xml

      <system.webServer>
          <urlCompression doStaticCompression="true" doDynamicCompression="true" />
      </system.webServer>

      ```


      还可以指定要压缩的特定动态和静态 MIME 类型。 有关详细信息，请参阅[简单 Azure 网站上的 httpCompression 设置](https://social.msdn.microsoft.com/Forums/azure/890b6d25-f7dd-4272-8970-da7798bcf25d/httpcompression-settings-on-a-simple-azure-website?forum=windowsazurewebsitespreview)，查看我们对一个论坛问题的回复。
  - question: >
      如何从本地环境迁移到应用服务？
    answer: >
      若要将站点从 Windows 和 Linux Web 服务器迁移到应用服务，可以使用 Azure App Service 迁移助手。 该迁移工具会根据需要在 Azure 中创建 Web 应用和数据库，然后发布内容。 有关详细信息，请参阅 [Azure App Service 迁移助手](https://appmigration.microsoft.com/)。
  - question: >
      为什么我的证书有效期为 11 个月，而不是一整年？
    answer: >-
      对于 2020/9/1 之后颁发的所有证书，最大持续时间现在为 397天。 对于 2020/9/1 之前颁发的证书，最大有效期为 825 天，除非续订、重新生成密钥等。2020/9/1 之后续订的证书都将受此更改的影响，并且用户可能会注意到其续订证书的有效期会缩短。

      GoDaddy 已实现一个订阅服务，该服务既能满足新要求，又遵循现有客户证书。 新颁发的证书在到期前三十天，该服务会自动颁发第二个证书，将持续时间延长到原始到期日期。 应用服务正在与 GoDaddy 合作以解决此更改问题，确保客户获得其证书的完整持续时间。
